# Generated by Django 5.2.14 on 2026-05-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part_1', models.CharField(default="Don't", help_text='Plain text before first <em>', max_length=100)),
                ('title_em_1', models.CharField(default='think', help_text='First italic word', max_length=100)),
                ('title_part_2', models.CharField(default=', begin', help_text='Plain text between the two <em> tags', max_length=100)),
                ('title_em_2', models.CharField(default='today', help_text='Second italic word', max_length=100)),
                ('title_suffix', models.CharField(default='!', help_text="Any trailing character (e.g. '!')", max_length=10)),
                ('description', models.TextField(default='Ut consectetur, metus sit amet aliquet placerat...')),
                ('button_text', models.CharField(default='Become a member', max_length=100)),
                ('button_url', models.CharField(default='#our-classes', max_length=200)),
            ],
            options={
                'verbose_name': 'Call to Action Section',
            },
        ),
        migrations.CreateModel(
            name='ClassesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Our', max_length=100)),
                ('section_title_em', models.CharField(default='Classes', max_length=100)),
                ('section_description', models.TextField(default='Nunc urna sem, laoreet ut metus id...')),
                ('view_all_text', models.CharField(default='View All Schedules', max_length=100)),
                ('view_all_url', models.CharField(default='#', max_length=200)),
            ],
            options={
                'verbose_name': 'Classes Section Heading',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_maps_embed_url', models.URLField(default='https://maps.google.com/maps?q=...', help_text='Paste the full iframe src URL from Google Maps > Share > Embed a map', max_length=1000)),
                ('map_height', models.PositiveIntegerField(default=600, help_text='Height of the map iframe in pixels')),
            ],
            options={
                'verbose_name': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('icon', models.ImageField(blank=True, help_text='Icon image shown on the left of the card', upload_to='features/')),
                ('title', models.CharField(help_text="e.g. 'Basic Fitness', 'Yoga Training'", max_length=150)),
                ('description', models.TextField()),
                ('link_text', models.CharField(default='Discover More', max_length=100)),
                ('link_url', models.CharField(default='#', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature Item',
                'verbose_name_plural': 'Feature Items',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Choose', max_length=100)),
                ('section_title_em', models.CharField(default='Program', help_text='Italic/highlighted word in section heading (<em>)', max_length=100)),
                ('section_description', models.TextField(default='Bendre’s Gymnastics Club is free CSS template for gyms and fitness centers.')),
            ],
            options={
                'verbose_name': 'Features Section Heading',
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='work harder, get stronger', help_text='Small text above the main headline (h6)', max_length=200)),
                ('title_plain', models.CharField(default='easy with our', help_text='Plain part of the main headline (h2)', max_length=200)),
                ('title_em', models.CharField(default='gym', help_text='Italic/highlighted part of the main headline (<em>)', max_length=100)),
                ('cta_button_text', models.CharField(default='Become a member', max_length=100)),
                ('cta_button_url', models.CharField(default='#features', max_length=200)),
                ('video_file', models.FileField(blank=True, help_text='Upload a .mp4 video for the banner background', upload_to='hero/')),
                ('video_url', models.URLField(blank=True, help_text='OR enter an external video URL (used if no file uploaded)')),
            ],
            options={
                'verbose_name': 'Hero Banner',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Classes', max_length=100)),
                ('section_title_em', models.CharField(default='Schedule', max_length=100)),
                ('section_description', models.TextField(default='Nunc urna sem, laoreet ut metus id...')),
            ],
            options={
                'verbose_name': 'Schedule Section Heading',
            },
        ),
        migrations.CreateModel(
            name='SiteFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(default='Copyright © 2024 Bendre’s Gymnastics Club', help_text='Copyright line. Year is shown as typed.', max_length=300)),
                ('show_designer_credit', models.BooleanField(default=True, help_text="Show 'Designed by TemplateMo' line")),
            ],
            options={
                'verbose_name': 'Site Footer',
            },
        ),
        migrations.CreateModel(
            name='SiteHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(default='Training', max_length=100)),
                ('logo_em_text', models.CharField(default='Studio', help_text='Italic part of the logo (inside <em> tag)', max_length=100)),
                ('logo_url', models.CharField(default='index.html', max_length=200)),
                ('nav_home_label', models.CharField(default='Home', max_length=50)),
                ('nav_about_label', models.CharField(default='About', max_length=50)),
                ('nav_classes_label', models.CharField(default='Classes', max_length=50)),
                ('nav_schedules_label', models.CharField(default='Schedules', max_length=50)),
                ('nav_contact_label', models.CharField(default='Contact', max_length=50)),
                ('nav_signup_label', models.CharField(default='Sign Up', max_length=50)),
                ('nav_signup_url', models.CharField(default='#', help_text='URL for the Sign Up button in the nav', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Header & Navigation',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('photo', models.ImageField(help_text='Portrait photo of the trainer', upload_to='trainers/')),
                ('photo_alt', models.CharField(blank=True, max_length=200)),
                ('specialty', models.CharField(help_text="Role shown above name, e.g. 'Strength Trainer'", max_length=150)),
                ('name', models.CharField(help_text="Full name, e.g. 'Bret D. Bowers'", max_length=150)),
                ('bio', models.TextField(help_text='Short bio paragraph')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('behance_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trainer',
                'verbose_name_plural': 'Trainers',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Expert', max_length=100)),
                ('section_title_em', models.CharField(default='Trainers', max_length=100)),
                ('section_description', models.TextField(default='Nunc urna sem, laoreet ut metus id...')),
            ],
            options={
                'verbose_name': 'Trainers Section Heading',
            },
        ),
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('tab_label', models.CharField(help_text="Label in the left-side tab list, e.g. 'First Training Class'", max_length=150)),
                ('tab_icon', models.ImageField(blank=True, upload_to='classes/tabs/')),
                ('name', models.CharField(help_text='Heading inside the tab content panel (h4)', max_length=150)),
                ('image', models.ImageField(help_text='Image shown in the class content panel', upload_to='classes/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('schedule_button_text', models.CharField(default='View Schedule', max_length=100)),
                ('schedule_url', models.CharField(default='#', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Training Class',
                'verbose_name_plural': 'Training Classes',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('class_name', models.CharField(help_text="e.g. 'Fitness Class', 'Yoga Training Class'", max_length=150)),
                ('slot_1_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('slot_1_time', models.CharField(help_text="e.g. '10:00AM - 11:30AM'", max_length=50)),
                ('slot_2_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('slot_2_time', models.CharField(help_text="e.g. '2:00PM - 3:30PM'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.trainer')),
            ],
            options={
                'verbose_name': 'Schedule Entry',
                'verbose_name_plural': 'Schedule Entries',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
